### ISSUE TITLE
How I build Pro-search with SvelteKit

### ISSUE THREAD

**Issue by bhekanik** [svelte-society/london#1]
** How I build Pro-search with SvelteKit

** Abstract of your talk

I've spent the past most of the evenings of the past few months building [Pro-search](https://www.pro-search.io), an easy to use advanced query builder for search engines, with SvelteKit. 

I really fell in love with svelte when I tried it out last year. So, when I started working on Pro-search, I decided to use SvelteKit and see how it fares in the real world despite me being much more familiar with React. This was also a way of fast tracking my learning and exposing myself to all the nooks that come with SvelteKit and svelte in general. I will talk about: 
1. My reasons for choosing SvelteKit. 
2. The issues I've encountered in the process
3. How I've solved or worked around the issues
4. What I've loved so far
5. Whether I will or will not be using SvelteKit again in the future for anything serious. 

** About the Talk

[ ] Things I need: Projector
[ ] Talk Length in Minutes (Approx): 30mins

** About You

[ ] Your Name: Bhekani Khumalo
[ ] Your Job: Software Engineer at Anaplan
[ ] Your Twitter Handle: @bhekanik
[ ] Your Location: London

**Comment by spences10** [comment]
Hey @bhekanik this sounds great!

We'd love to have you come tell us about Pro-search! Looks like a great outline!

Just an FYI, we've had to move the current date set from 24th Feb to a as yest undecided date sometime toward the end of March. Will that fit with you?

**Comment by bhekanik** [comment]
Hey @spences10 thank you. Yeah that works for me. I'll keep a look out for the new date when it's announced.

**Comment by spences10** [comment]
Hey @bhekanik just a heads up, the March event has now been moved a day earlier to the 23rd!

Let me know if that conflicts with your plans. 👍

Thanks

**Comment by bhekanik** [comment]
Hi @spences10 , unfortunately I'll be out of the country on the 23rd. I won't be able to make it.

**Comment by spences10** [comment]
Hey @bhekanik no worries! We'd love to have you speak at the next Meetup if you're available.

Thanks

**Comment by bhekanik** [comment]
Yes, definitely! Just let me know the dates.

**Comment by spences10** [comment]
Hey @bhekanik we're looking to do the next meetup toward the end of April (possibly 21st or 28th)

Would you be willing to do you talk then?

If so we can reopen this and have it scheduled for then??

**Comment by bhekanik** [comment]
Hi @spences10, yeah I can do those dates.

**Comment by spences10** [comment]
Hey @bhekanik we've had the venue confirmed

Can you confirm you'll be available to do the talk on April 28th 2022?

**Comment by bhekanik** [comment]
Hey @spences10, yeah I'm available. (Sidenote, the 28th is my birthday :))
