### ISSUE TITLE
Micro-frontends with Svelte & Module Federation

### ISSUE THREAD

**Issue by gioboa** [svelte-society/london#14]
## Micro-frontends with Svelte & Module Federation

Microservices nowadays is a well known concept and maybe you are using it in your current company.<br>Do you know that now you can apply similar ideas in the Frontend?<br>Today we already divide the Frontend into several components at development time, but at compile time these components are merged into one monolithic Frontend and this is where this new architecture comes into play.<br>In this talk we will understand the reasons behind micro-frontends and we will also explore one of the most interesting ways of applying them using Module Federation and Svelte

### About the Talk
- [x] Things I need (Projector, etc) - Projector ( _I will hold the in person talk_ )
- [x] Talk Length in Minutes (Approx) - 30min

### About You
- [x] Your Name - Giorgio Boa
- [x] Your Job - Full stack developer @ Claranet Italia
- [x] Your Twitter Handle - @giorgio_boa
- [x] Your Location - Treviso, Italy

**Comment by spences10** [comment]
Thank you sooo much @gioboa 🙏

**Comment by gioboa** [comment]
It was a pleasure for me 💪
