### ISSUE TITLE
Svelte - a shortcut to a11y? 

### ISSUE THREAD

**Issue by josefineschaefer** [svelte-society/london#16]
# Svelte - s shortcut to a11y? 

Svelte has been described as an “accessibility-first-framework”, yet its compiler warnings cover only a fragment of the issues at hand. In this talk, I’d like to explore how accessible Svelte really is and more importantly, have a look at what you can do to bridge the gap. Ideas include checking both automatically and manually for issues the compiler might overlook, like color contrast, keyboard accessibility and semantics.  

approximate length: 15 min

Josefine Schaefer
Developer Relations Engineer
@JsfnSchfr
Hamburg, Germany

**Comment by spences10** [comment]
Hey @josefineschaefer thanks for adding your talk! 🙏

Do you have a preference on when you would like to do it?

The events are usually at the end of each month, around the 20th, they are streamed on the Svelte Society YouTube channel and we use Streamyard for both in person and remote talks

**Comment by josefineschaefer** [comment]
Hi Scott, 
Thanks for the quick reply 🙌 
I could for example do the 20th of September for either one of the talks - whatever fits best with the other content.

**Comment by spences10** [comment]
Brillsies!

We have a venue confirmed for the 24th of this month.

One speaker confirmed, I can add this or #17 to that and the other for the September meetup.

Message on Discord or Twitter DM and I can go over the details for you 😊

**Comment by spences10** [comment]
Hey @josefineschaefer we're unable to get a venue for the September event, would you like to move this to October?

**Comment by spences10** [comment]
Close, after discussing with @josefineschaefer
