### ISSUE TITLE
DX magic in the world of Svelte

### ISSUE THREAD

**Issue by josefineschaefer** [svelte-society/london#17]
# DX magic in the world of Svelte

Developer Experience (DX) has become somewhat of a buzzword lately. But what is this trend really all about? 

Think about your experience with Svelte & Sveltekit. How things 'just work', and (for the most part) so quickly. In short: good DX feels like magic. Let's explore practical ways to create your tools with the best possible DX by having a look at real-world examples and see what we can do to improve developer experience in the Svelte community and beyond. 

approximate length: 20 min

Josefine Schaefer
Developer Relations Engineer 
@JsfnSchfr
Hamburg, Germany

**Comment by spences10** [comment]
Hi again @josefineschaefer, same detail as before, I'll copy paste here for continuity 😊

Hey @josefineschaefer thanks for adding your talk! 🙏

Do you have a preference on when you would like to do it?

The events are usually at the end of each month, around the 20th, they are streamed on the Svelte Society YouTube channel and we use Streamyard for both in person and remote talks

**Comment by spences10** [comment]
Hey @josefineschaefer do you still want to do this talk?

**Comment by josefineschaefer** [comment]
Hi @spences10 thanks for reaching out! No, I unfortunately currently don't have the capacity. You can close the issue. But that's for checking in 🙌
