### ISSUE TITLE
Building Efficient Sites with Partial Rehydration

### ISSUE THREAD

**Issue by endymion1818** [svelte-society/london#2]
** Talk Title
Building Efficient Sites with Partial Rehydration

** Abstract

There are a new generation of tools which will be coming to maturity in the next year or two. Their particular focus is on partial rehydration. We will take a look at:

- Why is partial rehydration an advantage
- How do I get started with these tools
- How can I leverage my knowledge of Svelte with partial rehydration

** About the Talk

I will need

- Access to Zoom or other video sharing
- Talk will be 30 mins long maximum

** About You

- Name: Benjamin Read
- Title: Software Engineer and Developer Relations at Webiny
- Twitter: @muzzlehatch_
- Location: Hertfordshire, UK

**Comment by spences10** [comment]
Thanks @endymion1818 I'll get this onto the Meetup agenda
