### ISSUE TITLE
Destroying the Client-Server Barrier using Typescript 🚀

### ISSUE THREAD

**Issue by akash-joshi** [svelte-society/london#26]
** Talk Title
Destroying the Client-Server Barrier using Typescript 🚀

** Abstract of your talk

Could you access the Prisma client on the frontend - without revealing any environment variables? This talk goes into my experimentation with Object proxies and websockets, allowing a developer to access server-side objects on the client, with type-safety.

I'll walk through how the proxying works, the type-safety features, and everything else which makes the library works. http://github.com/akash-joshi/rocketrpc

Use Cases:
- Define a type-safe API layer on the backend
- Share objects like ORM clients with the frontend 

** About the Talk

[ ] Things I need - Projector
[ ] Talk Length in Minutes (Approx) - 20

** About You

[ ] Akash Joshi
[ ] Software Engineer at Meta
[ ] @thewritingdev
[ ] London, UK

**Comment by spences10** [comment]
Awesome talk! Thanks, closing now
