### ISSUE TITLE
Realtime GraphQL with Houdini and Svelte [June 2023]

### ISSUE THREAD

**Issue by notrab** [svelte-society/london#28]
fyi @spences10 

**Talk Title**
* Realtime GraphQL with Houdini and Svelte

**Abstract of your talk**
* Build collaborative, multiplayer applications faster and easier than ever with realtime GraphQL.

**About the Talk**
- Needs: REMOTE
- Length: 20 minutes

**About You**
* Name: Vitaly Davidenko
* Engineer @ Grafbase
* `@vitalikda`
* Remote

**Availability**
* Anytime in June

**Comment by spences10** [comment]
Hey @notrab we're confirmed for June 21st, lmk if you're going to be presenting remote or in person

**Comment by notrab** [comment]
Hey @spences10 it'll be in person.

**Comment by notrab** [comment]
@vitalikda will now be presenting remotely on the same topic. It makes more sense given Vitaly has been working on a recent blog article and packages related to SSE.

@spences10 can you make sure someone reaches out to Vitaly to discuss the streaming/presentation options and arrange a tech check?

PS. I may still attend in-person FYI
