### ISSUE TITLE
KitQL - A simple GraphQL client, fully typed.

### ISSUE THREAD

**Issue by jycouet** [svelte-society/london#3]
## Talk Title
KitQL - A simple GraphQL client, fully typed.

## Abstract of your talk
Challenge: 
- Create a new SvelteKit project
- Interact with a public GraphQL endpoint
- Show SSR, Network & Caching queries
All this, with types and in 20 minutes!

## About the Talk
- [ ] Things I need: Remote connexion (let's organize this beforehand)
- [x] Talk Length in Minutes: 20 min + Q&A

## About You
- [x] Your Name: Jean-Yves Couët (French)
- [x] Your Job: Developer and more
- [x] Your Twitter Handle: jycouet
- [x] Your Location: Vienna Austria

**Comment by spences10** [comment]
Thanks @jycouet I'll get this onto the Meetup agenda 🥳
