### ISSUE TITLE
The wonders of creating a headless library for Svelte [August 2023]

### ISSUE THREAD

**Issue by TGlide** [svelte-society/london#33]
# The wonders of creating a headless library for Svelte 

** Abstract of your talk

Discussing the process and challenges of creating Melt UI, alongside some unique benefits that Svelte brings to the table (SvelteKit packaging, preprocessors, actions, etc). Together with a demonstration of the current builders available.

** About the Talk

- [ ] Things I need: Stream link
- Talk Length in Minutes (Approx) 10-20min

** About You

- Your Name: Thomas G. Lopes
- Your Job: Frontend Engineer @appwrite
- Your Twitter Handle: thomasglopes
- Your Location: Braga, Portugal

**Comment by akash-joshi** [comment]
Hey @TGlide ! We host talks either in-person or virtually (preferably in-person).

Talks are hosted near the end of every month. When would you like to give yours - starting from May?

**Comment by TGlide** [comment]
Hi @akash-joshi! End of May could work, but end of July would be perfect for me. Unfortunately, I would only be able to appear virtually.

**Comment by akash-joshi** [comment]
Thanks for replying! Will schedule you for July if that's okay

**Comment by TGlide** [comment]
> Thanks for replying! Will schedule you for July if that's okay

Sure, thank you!

**Comment by TGlide** [comment]
Hi! I don't think this talk is relevant anymore due to me discontinuing Radix Svelte active development. Sorry for the late notice!

If it's not an issue, I could talk about Melt UI, which is the other UI library I'm working on currently, and talk about headless UI libraries in general.

**Comment by TGlide** [comment]
Also, from what I'm reading in https://guild.host/events/svelte-london-july-2023-ulv266 the July event won't have speakers? Would the talk instead happen in a future event then?

**Comment by spences10** [comment]
Hey @TGlide if you can make the August one I'll get you on there, remote I guess?

Event in Aigust is scheduled for August 29th [Tuesday] we usually start around 19:00 BST let me know if you can make it

**Comment by TGlide** [comment]
> Hey @TGlide if you can make the August one I'll get you on there, remote I guess?
> 
> Event in Aigust is scheduled for August 29th [Tuesday] we usually start around 19:00 BST let me know if you can make it

Hi @spences10 yes, August works for me remotely 😄 

And is it okay for me to change the subject from Radix Svelte to Melt UI? I can update the issue description

**Comment by spences10** [comment]
Hey! Yeah, sure go for it! Leave the [August 2023] though, we use that for managing the event

Thanks

**Comment by akash-joshi** [comment]
Hey @TGlide we've added your talk to the event - https://guild.host/events/svelte-london-august-sfpuc8.

Could you please sign up for it and ping me here so it is linked to your profile? Thanks!

**Comment by TGlide** [comment]
> Hey @TGlide we've added your talk to the event - [guild.host/events/svelte-london-august-sfpuc8](https://guild.host/events/svelte-london-august-sfpuc8).
> 
> Could you please sign up for it and ping me here so it is linked to your profile? Thanks!

Hi @akash-joshi! The link you've sent me shows me a blank screen, not sure if this is normal?
![firefox_DGeyFJxvlE](https://github.com/svelte-society/london/assets/26071571/27404068-4135-42f5-9c8a-98170cd72c27)

**Comment by akash-joshi** [comment]
Hey @TGlide I apologize it was not public. Can you check now?

**Comment by TGlide** [comment]
> Hey @TGlide I apologize it was not public. Can you check now?

Done!

**Comment by TGlide** [comment]
@spences10 @akash-joshi is it okay if I change the length of the presentation to 15-30min?

**Comment by spences10** [comment]
> @spences10 @akash-joshi is it okay if I change the length of the presentation to 15-30min?

Yeah no problem, we go for two talks per event now so there's loads of wiggle room

**Comment by TGlide** [comment]
> > @spences10 @akash-joshi is it okay if I change the length of the presentation to 15-30min?
> 
> Yeah no problem, we go for two talks per event now so there's loads of wiggle room

Awesome, thank you!

**Comment by TGlide** [comment]
Hi! Just wondering if there's anything that I need to set-up beforehand, and when would I be getting the stream link? @spences10 @akash-joshi
