### ISSUE TITLE
Embedding Guild in Svelte [June 2023]

### ISSUE THREAD

**Issue by tazsingh** [svelte-society/london#34]
## Talk Title

Embedding Guild in Svelte

## Abstract of your talk

Communities come in different shapes and sizes. As the platform for communities, Guild needs to work wherever communities exist. A big part of accommodating that strategy is via embeddability, to take any part of our UI and put that wherever the community is.

This talk provides an overview of Guild and its new design principles, how it's been packaged for embeddability, and how it's been integrated into the Sveltekit Embed project.

## About the Talk

[ ] Things I need (Projector, etc)
- Projector
- Scott Spence 😄 

[ ] Talk Length in Minutes (Approx)
- 10 mins

** About You

[ ] Your Name
- Taz Singh

[ ] Your Job
- Founder @ Guild

[ ] Your Twitter Handle
- tazsingh

[ ] Your Location
- London

**Comment by akash-joshi** [comment]
Hey @tazsingh! We host talks either in-person or virtually (preferably in-person).

Talks are hosted near the end of every month. When would you like to give yours - starting from May?

Lmk if this was already discussed with Scott on Twitter :)

**Comment by spences10** [comment]
June would be good, I think we have @notrab coming to talk to us about Grafbase live queries in June

**Comment by tazsingh** [comment]
June 22nd? 👀  I can do that 🙌

**Comment by spences10** [comment]
Hey @tazsingh we're confirmed for June 21st, lmk if you're going to be presenting remote or in person

**Comment by tazsingh** [comment]
@spences10 Awesome, I'll be in town on the 21st so let's do it in-person!
