### ISSUE TITLE
Building Dashboards with Svelte

### ISSUE THREAD

**Issue by thisisthejay** [svelte-society/london#4]
** Talk Title

Building Dashboards with Svelte

** Abstract of your talk

I am a developer, legal engineer and Head of Legal Operations at a law firm.  I'm self taught and learning Svelte has given me the ability to build more complex applications.  We needed to build a dashboard to display our metrics and get insights and we picked SvelteKit.  

In the talk I'll cover:

- Why we chose SvelteKit for this project
- Loading data from an API
- Sharing state between components
- Some nice Svelte plugins from the ecosystem
- Implementing and re-rendering charts with Chart.js
- Auth0 integration

** About the Talk

[x] A projector if I can make it in person
[x] Talk Length in Minutes: 20min

** About You

[x] Your Name: Jay Smith
[x] Your Job: Legal Engineer, Head of Legal Operations
[x] Your Twitter Handle: @_thisisthejay
[x] Your Location: Bristol, UK

**Comment by spences10** [comment]
Looks great @thisisthejay, let me know if there's anything else you need.

I would love to meet in person but I do understand that there's a lot of moving parts with your situation 😊

**Comment by spences10** [comment]
Hey @thisisthejay we've had the venue confirmed.

Can you confirm you'll be available to do the talk on April 28th 2022?
