### ISSUE TITLE
Falling in Love with Frontend all over again

### ISSUE THREAD

**Issue by Roboroads** [svelte-society/london#43]
> **Important note:** This talk is aimed at non-Svelte developers to get them to consider Svelte in the future.

## Talk Title

Falling in Love with Frontend all over again

## Abstract of your talk

https://www.papercall.io/speakers/roboroads/speaker_talks/243455-falling-in-love-with-frontend-all-over-again

## Things I need (Projector, etc)

 - A (big) screen/projector accepting HDMI or USB-C.
 - Microphone depending on the amount of people
 - Talk length: 40mins without questions.

## About You

- Name: Robbin Schepers 
- Job: Lead Developer @ [Ordina](https://ordina.com)
- Twitter: Roboroads
- Location: The Netherlands

**Comment by akash-joshi** [comment]
Hey @Roboroads, would you be interested in giving a talk in either March or April?

**Comment by Roboroads** [comment]
Hey @akash-joshi - I'm not comfortable giving this talk anymore in preparation of runes. My talk really focusses on the magical reactivity.

**Comment by akash-joshi** [comment]
Would you prefer continuing with this talk once Runes are out?

**Comment by Roboroads** [comment]
It kinda depends on what Svelte 5 releases with. I might not give this talk anymore at all or refactor it to include why Svelte 5 is awesome depending on that :)

**Comment by spences10** [comment]
Ok, thanks @Roboroads I'll close this one then, thanks
