### ISSUE TITLE
How to introduce new technology at work (and why you maybe shouldn't) [August 2023]

### ISSUE THREAD

**Issue by lucy-m** [svelte-society/london#48]
## Talk Title

How to introduce new technology at work (and why you maybe shouldn't)

((The title is still WIP, I may want to change it soon. Wanted to get this submitted ASAP!))

## Abstract of your talk

 Picking up a new language or framework is always a fun side project, but bringing these into production software at work is always a challenge. It may not be compatible with other technologies you use. The project will need to be maintained for possibly years to come. You will have to convince the rest of your team it's a good idea and they should invest the time to learn.

At Codat, we have used React for our front ends for years but earlier this year we successfully did a project using Svelte. In this talk I will discuss why we decided to use Svelte, how to convince people to use a new language or framework, and why you maybe shouldn't.

## About the Talk

[ ] Things I need - Projector
[ ] Talk Length in Minutes - Aiming for 30-45 minutes

## About You

[ ] Your Name - Lucy Mair
[ ] Your Job - Senior software engineer
[ ] Your Twitter Handle - I don't have twitter
[ ] Your Location - Manchester, UK

I work at Codat so would prefer to do the talk on August 29th.

**Comment by akash-joshi** [comment]
Hi @lucy-m , thanks for submitting your talk. We're glad to share that you'll be able to present your talk at the 29th August meetup. We'll be updating the event with your talk's details

**Comment by akash-joshi** [comment]
Once you sign up for the event here - https://guild.host/events/svelte-london-august-sfpuc8 - we should be able to link to your Guild profile. Let me know when you do that, thanks!

**Comment by akash-joshi** [comment]
All okay for the 29th so far? @lucy-m
