### ISSUE TITLE
Excerpts from iJS London Conference Talk

### ISSUE THREAD

**Issue by mvolkmann** [svelte-society/london#5]
** Talk Title
Excerpts from iJS London Conference Talk

** Abstract of your talk

- What is the significance of Svelte being a compiler?
- Interesting use of reactive statements
- Custom animation example
- Summary of component communication options

** About the Talk

[X] Things I need (Projector, etc) - just a projector
[X] Talk Length in Minutes (Approx) - 10

** About You

[X] Your Name - Mark Volkmann
[X] Your Job - Partner and Distinguished Software Engineer at Object Computing, Inc.
[X] Your Twitter Handle - @mark_volkmann
[X] Your Location - St. Louis, Missouri  USA

**Comment by spences10** [comment]
Thanks @mvolkmann!

Can you confirm you'll be available to do the talk on April 28th 2022?

**Comment by mvolkmann** [comment]
Unless I get lost trying to find a venue I should be there. It will be my first time in London. :-)

R. Mark Volkmann
Object Computing, Inc.

**Comment by spences10** [comment]
Brilliant! Ok, you can get any of the organisers on the Svelte Discord if you need any help 👍

**Comment by mvolkmann** [comment]
Great! My flight leaves this Friday morning, so I'll have almost a whole week to learn about London public transportation. I'll be staying at the Park Plaza Victoria Hotel across the street from Victoria Station.
