### ISSUE TITLE
Everything old is new again: my first month of Svelte

### ISSUE THREAD

**Issue by lovell** [svelte-society/london#59]
** Talk Title

Everything old is new again: my first month of Svelte

** Abstract of your talk

A reflection on how what I've learnt about Svelte in the last few weeks fits into the context of what I've learnt in the last 30 years of software development.

Although perhaps more suited to those new to Svelte or Svelte-curious, it will hopefully also still be of interest to a wider audience.

** About the Talk

[ ] Things I need (Projector, etc)

I'm not planning to do any live coding so it's probably easier for me to provide a URL to access the slides on the day and use a laptop that's already set up and known to be working with existing AV equipment. Happy to bring a laptop with standard HDMI output if required.

[ ] Talk Length in Minutes (Approx)

Not sure yet, the longer I have to plan the shorter it will be, but will try to aim for around 20 minutes.

** About You

[ ] Your Name

Lovell Fuller

[ ] Your Job

Freelance software developer

[ ] Your ~~Twitter Handle~~ Website

https://lovell.info/

[ ] Your Location

London, UK

**Comment by akash-joshi** [comment]
Hey @lovell, we've scheduled you for the March 28th event. Does that work with you?

**Comment by lovell** [comment]
Yes, that's good for me, thank you.

**Comment by spences10** [comment]
Awesome talk @lovell, I'll ping you when we have the video uploaded 🙏
