### ISSUE TITLE
The Hackathon Survival Guide

### ISSUE THREAD

**Issue by slarsendisney** [svelte-society/london#6]
** Talk Title
### The Hackathon Survival Guide

** Abstract of your talk

A mixture of hackathon experiences, projects and some pearls of wisdom stolen from my new book. Come learn about my journey to $20,000 in hackathon prize money. 

** About the Talk
I need  a projector! 
20 mins in duration - I'll take questions too!

** About You

Sam Larsen-DIsney
Software Engineer @ Amplitude
@samlarsendisney
London

**Comment by spences10** [comment]
Thanks Sam! Awesome talk
