### ISSUE TITLE
[3 stories of walking in the fire with my sveltekit project]

### ISSUE THREAD

**Issue by RowanAldean** [svelte-society/london#60]
**Talk Title** 
3 stories of walking in the fire with my SvelteKit project

**Abstract of your talk**
3 small stories on the most recent hurdles (of many) that had to be overcome and an audience question at the end.
- Dealing with PostGIS for Postgres using DrizzleORM (this is an ongoing issue for the Drizzle team)
- Dealing with dynamic query building for DrizzleORM (another ongoing issue which is non-standard for most of these ORM libs... chaining `where` based on your biz conditions)
- Dealing with slide animation in SvelteKit (wanting to not need to prefetch the next listing but still have a pretty "card comes in" transition).
    - This will lead to my final question, which is suggestions on how I can achieve this as I plan on introducing swiper js to support cards properly. I am sure there's a way to have some pending state on transition and then animate in the data once fetched 🤔 

**A short overview of your talk we can put on the event page**
Rowan launched his MVP to early access using SvelteKit and serverless infrastructure. He'll share 3 stories of workarounds that might be relevant if you're working with DrizzleORM or SvelteKit.

**About the Talk**

_Things I need:_ Projector, An Audience
_Talk length in minutes:_ 30mins hard limit - 10 mins per story max? 

**About You**
Rowan Aldean
Founder @ Casa - Bootstrapped
https://www.linkedin.com/in/raldean/
London

**Comment by spences10** [comment]
Thanks @RowanAldean 🙌
