### ISSUE TITLE
Auth in SvelteKit, the hard & easy ways

### ISSUE THREAD

**Issue by JitPackJoyride** [svelte-society/london#63]
# Talk Title

Auth in SvelteKit, the hard way & the easy way

## Abstract of your talk

How to implement authentication in SvelteKit. We'll implement everything ourselves from scratch, with the PKCE flow. Then, we'll see how simple it can get with EdgeDB.

** About the Talk

[x] Things I need: Projector, Mic
[x] Talk Length in Minutes (Approx): 30

** About You

[x] Your Name: Ajit Krishna N.R.
[x] Your Job: Product Engineer
[x] Your Twitter Handle: JitPackJoyride
[x] Your Location: London

**Comment by spences10** [comment]
Thanks @JitPackJoyride 🙌
