### ISSUE TITLE
SvelteKit and Pocketbase

### ISSUE THREAD

**Issue by ghostdevv** [svelte-society/london#64]
### Talk Title

SvelteKit and Pocketbase

### Abstract of your talk

Every side project starts out with a question: "What's the BEST tech stack" - how silly! there's no answer right... Meet Pocketbase, an open source go backend providing you everything you need for your app (except users).

#### Things I need:

Projector & Mic

#### Talk Length in Minutes (Approx):

20 mins probably (will clarify later)

### About You

Your Name: `Willow (GHOST)`
Your Job: `Yes`
Your Twitter Handle: `onlyspaceghost`
Your Location: `UK`

**Comment by ghostdevv** [comment]
If the talk is accepted I'll write a proper title/description 🙏

**Comment by spences10** [comment]
Of course it's accepted!

**Comment by akash-joshi** [comment]
@ghostdevv up for May 2024?

**Comment by ghostdevv** [comment]
Sounds good @akash-joshi - updated the title & description
