### ISSUE TITLE
[How Computers draw]

### ISSUE THREAD

**Issue by alvinometric** [svelte-society/london#65]
**Talk Title**

How computers draw

**Abstract of your talk**

Not strictly Svelte, but should be interesting for people who like "visual stuff"

https://guild.host/presentations/how-computers-draw-g8y8ej

**About the Talk**

Things I need: HDMI, projector/screen
Talk Length in Minutes: about 15-20

**About You**

Your Name: `Alvin Bryan`
Your Job: `Developer Advocate at Unleash`
Your Twitter Handle: `@hola_alvin`
Your Location: `Manchester 🇬🇧`

**Comment by akash-joshi** [comment]
How much Svelte could you inject into it? Since Svelte was primarily built for computer graphics as well, this might be a good fit.

**Comment by alvinometric** [comment]
This touches on topics that Svelte developer like (curves, fonts, charts, etc) but I can't really put any Svelte in it, or I'll be talking forever.

Totally OK if that's incompatible
