### ISSUE TITLE
[suggestion] four alternative talk ideas

### ISSUE THREAD

**Issue by article7** [svelte-society/london#67]
Hi – just wanted to submit my talk ideas. I totally understand if none of the following are suitable, but here’s what I’ve got:

### Realtime chat with Svelte

AttendZen’s virtual event sessions and attendee app have simple chat built-in. We use Twilio Sync as a realtime/websockets provider, so it could be interesting to explore this and check out some code. I’d like to have a working chat for the talk embedded in the slides, with a URL that attendees in-person and online could use to participate.

### Building a virtual event studio using Svelte

Delving a little into our solution for managing live-streamed presentations in-browser – a bit like Streamyard. Using Svelte to manage participants and the stage, with LiveKit to handle WebRTC, Twilio Sync to handle realtime coordination, and Mux to take care of streaming the end result.

### Creating a PWA with Svelte

We’ve made an event check-in app as a PWA, and I’m working now on an attendee app also delivered as a PWA. I’m not sure if this is a perfect fit for the meet-up, as we’re not (yet) using SvelteKit for them – but there might be some useful takeaways regarding install prompts, push notifications and caching?

### Making a drag-and-drop website builder in Svelte

Part of our platform is a simple event website builder, where you can drag components onto a preview and edit them, with Svelte updating the preview in realtime. Probably the most interesting quirk here is that the preview is rendered smaller than the real size of the page, in an iframe, which led to a few challenges.

### About You

Andrew Green
Developer, AttendZen
Sidcup / London

Not on Twitter any more (Elon) but vaguely on Threads @shedside

**Comment by spences10** [comment]
only 1? 😔

they all sound great, and if you're willing to put in the time for each, then happy to have these in the repo to pick from when you are up to it @article7 

so four suggestions as individual issues

or

if you only want to do the one then I'll leave that to you to pick which best fits here and remove the other suggestions

**Comment by article7** [comment]
Fab – I'm happy to do all 4 with some gaps! That's assuming of course that I don't completely crash and burn on the first, which isn't entirely unlikely. I'll add them as separate issues here shortly. Thanks!

**Comment by spences10** [comment]
Go for it!

I'll communicate with you on when is best to do them, thanks!

**Comment by spences10** [comment]
@article7 please put in these talks as separate issues and close this one

thanks

**Comment by article7** [comment]
Separate issues added – thanks!
