### ISSUE TITLE
Building a virtual event studio using Svelte

### ISSUE THREAD

**Issue by article7** [svelte-society/london#70]
### Talk Title

Building a virtual event studio using Svelte

### Abstract of your talk

Delving a little into AttendZen’s solution for managing live-streamed presentations in-browser. Using Svelte to manage participants and the stage, with LiveKit to handle WebRTC, Twilio Sync to handle realtime coordination, and Mux to take care of streaming the end result.

### About the Talk

I'll need a projector, but I'll bring a laptop with the slides and a logged-in Studio session.

There's a fair bit to cover, so I'd expect the talk to last about 30 mins.

### About You

Andrew Green
Developer, AttendZen
Sidcup / London

Not on Twitter any more (Elon) but halfheartedly on Threads @shedside

**Comment by spences10** [comment]
Delivered September event

Thanks @article7 🫶
