### ISSUE TITLE
The joy of side projects ✨

### ISSUE THREAD

**Issue by mayariii** [svelte-society/london#75]
** Talk Title

The joy of side projects

** Abstract of your talk

A showcase of my Svelte side projects (including the silly ones). What I learned from a community of builders & my biggest side project yet. 

** About the Talk

[ ] Projector
[ ] 15 - 20 mins

** About You

[ ] Maya Avendaño
[ ] Frontend Engineer [Outverse](https://www.outverse.com/)
[ ] [@mayaisxyz](https://x.com/mayaisxyz) // [mayari.io](https://www.mayari.io)
[ ] Loughborough, UK

**Comment by spences10** [comment]
Delivered September event

Thanks @mayariii 🫶
