### ISSUE TITLE
Herd your async tasks!

### ISSUE THREAD

**Issue by paoloricciuti** [svelte-society/london#77]
**Herd your async tasks!**
Async tasks are a PITA to work on...they are messy, all over the place and the kinda smell bad. Just like sheep. But they can be tamed by an experienced ~shepherd~developer especially if they are accompanied by their trusty sheepdog.

[x] Things I need (Projector, etc): projector
[x] Talk Length in Minutes (Approx): 30ish

** About You

[x] Your Name: Paolo Ricciuti
[x] Your Job: Senior Software Engineer at Mainmatter
[x] Your Twitter Handle: @PaoloRicciuti
[x] Your Location: Campobasso, Italy

**Comment by spences10** [comment]
Thanks @paoloricciuti
